name = "rompfortherescues"
compatibility_date = "2024-09-23"
pages_build_output_dir = "public"
compatibility_flags = [ "nodejs_compat" ]

[vars]
# Non-secret config
FROM_EMAIL  = "donotreply@rompfortherescues.org"
CC_EMAIL    = "rompfortherescues@gmail.com"
FROM_NAME   = "rompfortherescues.org"
REPLY_TO    = "rompfortherescues@gmail.com"
BCC_EMAIL   = "rogerdtinsley@gmail.com"

